// Backlogs de proyectos ficticios para el Kanban Game.
// Cada historia tiene título + estimación CURADA (valor de negocio 1-5, esfuerzo
// Fibonacci 1/2/3/5/8/13) coherente con el título, para que la priorización
// (Valor/Esfuerzo) tenga sentido y el equipo pueda discutir qué hacer primero.
//
// Las historias se asignan por ORDEN al número de historia (deterministas: la
// ronda sin WIP y la ronda con WIP ven exactamente las mismas). Si se agotan,
// el motor cae a "Tarea genérica N" con estimación aleatoria.

/** Atajo: story(título, valor, esfuerzo). */
const s = (t, b, d) => ({ t, b, d });

export const BACKLOGS = [
  {
    id: 'tiendaya',
    name: 'TiendaYa',
    emoji: '🛒',
    desc: 'E-commerce de moda',
    stories: [
      s('Recuperar contraseña por email', 4, 2),
      s('Botón "añadir al carrito" en el listado', 4, 2),
      s('Filtro por talla y color', 4, 3),
      s('Buscador con autocompletado', 4, 5),
      s('Pasarela de pago con tarjeta', 5, 5),
      s('Pago con PayPal', 4, 3),
      s('Cálculo de gastos de envío', 3, 3),
      s('Cupones de descuento', 4, 3),
      s('Ficha de producto con galería', 3, 3),
      s('Reseñas y valoraciones', 3, 5),
      s('Lista de deseos', 2, 2),
      s('Histórico de pedidos del cliente', 3, 3),
      s('Seguimiento del envío', 4, 3),
      s('Devoluciones online', 4, 5),
      s('Stock en tiempo real', 4, 5),
      s('Avisar cuando vuelva a haber stock', 2, 2),
      s('Recomendaciones "también te puede gustar"', 3, 8),
      s('Migrar el catálogo al nuevo CMS', 2, 13),
      s('Panel de administración de productos', 3, 8),
      s('Importación masiva de productos por CSV', 2, 5),
      s('Etiquetas de "rebajas" y "novedad"', 3, 1),
      s('Tallas guía interactiva', 2, 3),
      s('Login con Google', 4, 3),
      s('Carrito persistente entre dispositivos', 3, 5),
      s('Checkout en un solo paso', 5, 8),
      s('Factura en PDF', 3, 2),
      s('Notificaciones de pedido por email', 3, 2),
      s('Modo oscuro de la web', 1, 3),
      s('Banner de cookies RGPD', 2, 2),
      s('Integración con transportista', 4, 8),
      s('Reembolsos automáticos', 3, 5),
      s('Programa de puntos de fidelidad', 3, 8),
      s('Tarjetas regalo', 2, 5),
      s('Comparador de productos', 2, 5),
      s('Optimizar imágenes (rendimiento)', 3, 3),
      s('Migrar la base de datos a la nube', 2, 13),
      s('Multidioma (ES/EN/FR)', 3, 8),
      s('Test A/B del botón de compra', 2, 3),
      s('Chat de soporte', 3, 5),
      s('Panel de métricas de ventas', 3, 5),
    ],
  },
  {
    id: 'fittrack',
    name: 'FitTrack',
    emoji: '📱',
    desc: 'App de fitness y hábitos',
    stories: [
      s('Registro de usuario', 4, 2),
      s('Onboarding con objetivos', 3, 3),
      s('Contador de pasos diario', 4, 3),
      s('Registrar entrenamiento', 4, 3),
      s('Biblioteca de ejercicios', 3, 5),
      s('Temporizador de descanso', 3, 2),
      s('Rachas de días seguidos', 3, 2),
      s('Recordatorios de hidratación', 2, 2),
      s('Gráfica de progreso de peso', 4, 3),
      s('Sincronizar con smartwatch', 4, 8),
      s('Plan de entrenamiento personalizado', 5, 8),
      s('Compartir logro en redes', 2, 3),
      s('Calorías por comida', 3, 5),
      s('Escáner de código de barras de alimentos', 3, 8),
      s('Notificación de objetivo cumplido', 3, 1),
      s('Modo sin conexión', 3, 8),
      s('Login con Apple', 4, 3),
      s('Recuperar contraseña', 4, 2),
      s('Retos entre amigos', 3, 8),
      s('Ranking semanal', 2, 5),
      s('Exportar datos a Salud/Google Fit', 3, 5),
      s('Vídeos de los ejercicios', 3, 8),
      s('Suscripción premium', 5, 8),
      s('Prueba gratuita de 7 días', 4, 3),
      s('Widget de la pantalla de inicio', 2, 3),
      s('Migrar usuarios del sistema antiguo', 2, 13),
      s('Notificaciones push', 3, 5),
      s('Modo oscuro', 1, 2),
      s('Ajustes de privacidad', 3, 3),
      s('Frecuencia cardíaca en tiempo real', 3, 8),
      s('Diario de ánimo', 2, 3),
      s('Recordatorio de entrenamiento', 3, 1),
      s('Estadísticas mensuales', 3, 3),
      s('Integración con Strava', 3, 5),
      s('Pantalla de perfil', 2, 2),
      s('Insignias por logros', 2, 3),
      s('Rediseño de la home', 2, 8),
      s('Tutorial interactivo', 2, 3),
      s('Soporte multidispositivo', 3, 8),
      s('Copia de seguridad en la nube', 3, 5),
    ],
  },
  {
    id: 'clinicloud',
    name: 'ClíniCloud',
    emoji: '🏥',
    desc: 'Gestión de clínica',
    stories: [
      s('Alta de paciente', 4, 3),
      s('Buscar paciente por DNI', 4, 2),
      s('Agenda de citas', 5, 5),
      s('Recordatorio de cita por SMS', 4, 3),
      s('Sala de espera virtual', 3, 5),
      s('Historia clínica del paciente', 5, 8),
      s('Recetas electrónicas', 4, 8),
      s('Firma digital del consentimiento', 4, 5),
      s('Facturación a aseguradoras', 4, 8),
      s('Cuadrante de turnos del personal', 3, 5),
      s('Login con tarjeta sanitaria', 4, 5),
      s('Recuperar acceso del profesional', 4, 2),
      s('Subir resultados de analítica', 3, 3),
      s('Visor de imágenes médicas', 3, 8),
      s('Avisar de alergias del paciente', 5, 2),
      s('Panel del médico con citas del día', 4, 3),
      s('Teleconsulta por vídeo', 4, 13),
      s('Exportar historia clínica en PDF', 3, 3),
      s('Cumplimiento RGPD de datos sensibles', 5, 8),
      s('Auditoría de accesos', 3, 5),
      s('Migrar historiales del sistema antiguo', 2, 13),
      s('Cobro con datáfono', 3, 3),
      s('Lista de espera por especialidad', 3, 3),
      s('Notas de evolución', 3, 2),
      s('Plantillas de informe', 2, 3),
      s('Consentimientos por tipo de prueba', 2, 5),
      s('Recordatorio de revisión anual', 3, 2),
      s('Gestión de bajas laborales', 3, 5),
      s('Cuadro de mando de ocupación', 3, 5),
      s('Reprogramar cita arrastrando', 3, 5),
      s('Encuesta de satisfacción', 2, 2),
      s('Control de stock de fármacos', 3, 5),
      s('Alertas de caducidad de medicación', 3, 3),
      s('Portal del paciente', 4, 8),
      s('Doble factor para el personal', 4, 3),
      s('Copia de seguridad cifrada', 4, 5),
      s('Integración con laboratorio externo', 3, 8),
      s('Estadísticas de diagnósticos', 2, 5),
      s('Modo accesible (alto contraste)', 3, 2),
      s('Multisede de la clínica', 3, 13),
    ],
  },
  {
    id: 'pixelarena',
    name: 'PixelArena',
    emoji: '🎮',
    desc: 'Plataforma de torneos',
    stories: [
      s('Registro de jugador', 4, 2),
      s('Crear un torneo', 5, 5),
      s('Inscribirse a un torneo', 4, 3),
      s('Bracket de eliminatorias', 4, 8),
      s('Emparejamiento automático', 4, 8),
      s('Reportar resultado de partida', 4, 3),
      s('Chat de la sala del torneo', 3, 5),
      s('Perfil con estadísticas', 3, 3),
      s('Ranking global ELO', 4, 8),
      s('Login con Discord', 4, 3),
      s('Recuperar cuenta', 4, 2),
      s('Sistema antitrampas básico', 4, 13),
      s('Streaming embebido de la final', 3, 5),
      s('Premios y monedero virtual', 3, 8),
      s('Notificar inicio de partida', 4, 2),
      s('Historial de partidas', 3, 3),
      s('Espectadores en directo', 3, 8),
      s('Insignias y logros', 2, 3),
      s('Reglas personalizadas por torneo', 3, 5),
      s('Moderación y reportes', 3, 5),
      s('Migrar rankings de la beta', 2, 13),
      s('Panel de organizador', 3, 5),
      s('Calendario de torneos', 3, 3),
      s('Equipos y clanes', 3, 8),
      s('Invitar amigos', 2, 2),
      s('Modo práctica', 2, 3),
      s('Replays de partidas', 2, 8),
      s('Verificación de edad', 3, 2),
      s('Suscripción de pago', 5, 8),
      s('Skins y personalización', 2, 5),
      s('Notificaciones push', 3, 3),
      s('Modo oscuro', 1, 1),
      s('Soporte de mando', 2, 5),
      s('Tablón de anuncios', 2, 2),
      s('Penalización por abandono', 3, 3),
      s('Integración con Twitch', 3, 5),
      s('Estadísticas avanzadas premium', 3, 8),
      s('Salas privadas con contraseña', 3, 3),
      s('Multi-idioma', 2, 8),
      s('Rediseño del lobby', 2, 8),
    ],
  },
];

/** Devuelve un backlog por id (o null). */
export function backlogById(id) {
  return BACKLOGS.find((b) => b.id === id) || null;
}

/** Lista ligera {id, name, emoji, desc, count} para selectores. */
export function backlogOptions() {
  return BACKLOGS.map((b) => ({ id: b.id, name: b.name, emoji: b.emoji, desc: b.desc, count: b.stories.length }));
}

/** Títulos para historias Urgent (expedite). */
export const URGENT_TITLES = [
  'Caída en producción',
  'Fallo crítico en el pago',
  'Fuga de datos detectada',
  'El login no funciona',
  'Pico de tráfico inesperado',
];
